In [1]:
import csv
import pandas as pd

lectura = open("CYP2D6_Diplotype_Phenotype_Table.xlsx")

In [2]:
df_resumen = pd.read_csv('tabla_mutaciones.csv')

In [3]:
ancestral = dict(zip(df_resumen["Polimorfismo"], df_resumen["Base ancestral"])) #Lo onvierte en un dict tipo: {'CYP2D6*17': 'G', 'DPYD*2A': 'C', ...} para comparar base ancestral


#Sacar nombre del alelo mutado
def etiqueta_mutada(polimorfismo):
    """ Convierte p.ej "CYP2D6*17" a "*17" """
    if "*" in polimorfismo:
        return "*" + polimorfismo.split("*")[1]
    return "*" +polimorfismo.split("_")[1] #HapB3 p.ej tiene _ en vez de *


#Sacar el nombre del gen
def gen_sin_alelo(polimorfismo):
    """ Convierte p.ej "CYP2D6*17" a "CYP2D6" """
    if "*" in polimorfismo:
        return polimorfismo.split("*")[0]
    return polimorfismo.split("_")[0] 


#Función para convertir genotipo a números
def letras_a_nums(polimorfismo, genotipo):
    """ Convierte p.ej "G/A" a "*1/*17" """
    wild_type = ancestral[polimorfismo]
    mut = etiqueta_mutada(polimorfismo)
    alelos = ["*1" if b == wild_type else mut for b in genotipo.split("/")]
    alelos.sort(key = lambda a:a != "*1") #Para que el alelo siempre sea con la estructura *1/*17
    return alelos[0] + "/" + alelos[1]

In [4]:
with open("Genotype Matrix.csv", mode = "r") as file:
    lector = csv.reader(file, delimiter=";")
    pacientes = {}
    cabecera = next(lector) #Para saltar el encabezado
    for fila in lector: 
        cod_paciente = fila[0]
        pacientes[cod_paciente] = {} #Por cada paciente se crea un diccionario
        for columna, elemento in zip(cabecera, fila):
            if columna != "Sample/Assay": #Para no guardar el ID del paciente ya que ya es la clave
                pacientes[cod_paciente][columna] = elemento

    print(pacientes)

#Para juntar las mutaciones d eun mismo gen, yo añadiría un, si empieza por CYP2D6 añadir a lista CYP2D6 y luego que sea la lista lo que añadimos en el diccionario

{'DPD932': {'CYP2D6*3': 'T/T', 'CYP2D6*4': 'C/C', 'CYP2D6*17': 'G/A', 'CYP2D6*41': 'C/C', 'DPYD*2A': 'C/C', 'DPYD*13': 'A/A', 'DPYD_HapB3': 'C/T', 'DPYD_D949V': 'T/T', 'UGT1A1*80': 'C/C'}, 'DPD933': {'CYP2D6*3': 'T/T', 'CYP2D6*4': 'C/C', 'CYP2D6*17': 'A/A', 'CYP2D6*41': 'C/C', 'DPYD*2A': 'C/C', 'DPYD*13': 'A/A', 'DPYD_HapB3': 'C/C', 'DPYD_D949V': 'T/T', 'UGT1A1*80': 'C/T'}, 'DPD934': {'CYP2D6*3': 'T/T', 'CYP2D6*4': 'C/T', 'CYP2D6*17': 'G/G', 'CYP2D6*41': 'C/C', 'DPYD*2A': 'C/C', 'DPYD*13': 'A/A', 'DPYD_HapB3': 'C/C', 'DPYD_D949V': 'T/T', 'UGT1A1*80': 'C/C'}, 'DPD935': {'CYP2D6*3': 'T/T', 'CYP2D6*4': 'C/C', 'CYP2D6*17': 'G/G', 'CYP2D6*41': 'C/C', 'DPYD*2A': 'C/C', 'DPYD*13': 'A/A', 'DPYD_HapB3': 'C/C', 'DPYD_D949V': 'T/T', 'UGT1A1*80': 'C/T'}, 'DPD936': {'CYP2D6*3': 'T/T', 'CYP2D6*4': 'C/C', 'CYP2D6*17': 'G/G', 'CYP2D6*41': 'C/T', 'DPYD*2A': 'C/C', 'DPYD*13': 'A/A', 'DPYD_HapB3': 'C/C', 'DPYD_D949V': 'T/T', 'UGT1A1*80': 'C/T'}, 'DPD937': {'CYP2D6*3': 'T/T', 'CYP2D6*4': 'C/C', 'CYP2D6*17': 'G/G', 'CYP2D6*41': 'C/C', 'DPYD*2A': 'C/C', 'DPYD*13': 'A/A', 'DPYD_HapB3': 'C/C', 'DPYD_D949V': 'T/T', 'UGT1A1*80': 'C/C'}, 'DPD938': {'CYP2D6*3': 'T/T', 'CYP2D6*4': 'C/C', 'CYP2D6*17': 'G/G', 'CYP2D6*41': 'C/C', 'DPYD*2A': 'C/C', 'DPYD*13': 'A/A', 'DPYD_HapB3': 'C/C', 'DPYD_D949V': 'T/T', 'UGT1A1*80': 'C/C'}, 'DPD939': {'CYP2D6*3': 'T/T', 'CYP2D6*4': 'C/C', 'CYP2D6*17': 'G/G', 'CYP2D6*41': 'C/T', 'DPYD*2A': 'C/C', 'DPYD*13': 'A/A', 'DPYD_HapB3': 'C/T', 'DPYD_D949V': 'T/T', 'UGT1A1*80': 'T/T'}, 'DPD940': {'CYP2D6*3': 'T/-', 'CYP2D6*4': 'C/C', 'CYP2D6*17': 'G/G', 'CYP2D6*41': 'C/C', 'DPYD*2A': 'C/C', 'DPYD*13': 'A/A', 'DPYD_HapB3': 'C/C', 'DPYD_D949V': 'T/T', 'UGT1A1*80': 'C/T'}, 'DPD941': {'CYP2D6*3': 'T/T', 'CYP2D6*4': 'T/T', 'CYP2D6*17': 'G/G', 'CYP2D6*41': 'C/C', 'DPYD*2A': 'C/C', 'DPYD*13': 'A/A', 'DPYD_HapB3': 'C/C', 'DPYD_D949V': 'T/T', 'UGT1A1*80': 'C/T'}, 'DPD942': {'CYP2D6*3': 'T/T', 'CYP2D6*4': 'C/C', 'CYP2D6*17': 'G/G', 'CYP2D6*41': 'C/T', 'DPYD*2A': 'C/C', 'DPYD*13': 'A/A', 'DPYD_HapB3': 'C/T', 'DPYD_D949V': 'T/T', 'UGT1A1*80': 'C/T'}, 'DPD943': {'CYP2D6*3': 'T/T', 'CYP2D6*4': 'C/C', 'CYP2D6*17': 'G/G', 'CYP2D6*41': 'C/T', 'DPYD*2A': 'C/C', 'DPYD*13': 'A/A', 'DPYD_HapB3': 'C/T', 'DPYD_D949V': 'T/T', 'UGT1A1*80': 'C/T'}, 'DPD944': {'CYP2D6*3': 'T/T', 'CYP2D6*4': 'C/C', 'CYP2D6*17': 'G/G', 'CYP2D6*41': 'C/C', 'DPYD*2A': 'C/C', 'DPYD*13': 'A/A', 'DPYD_HapB3': 'C/C', 'DPYD_D949V': 'T/T', 'UGT1A1*80': 'C/C'}, 'DPD945': {'CYP2D6*3': 'T/T', 'CYP2D6*4': 'C/C', 'CYP2D6*17': 'G/G', 'CYP2D6*41': 'C/C', 'DPYD*2A': 'C/C', 'DPYD*13': 'A/A', 'DPYD_HapB3': 'C/C', 'DPYD_D949V': 'T/T', 'UGT1A1*80': 'C/C'}, 'DPD946': {'CYP2D6*3': 'T/T', 'CYP2D6*4': 'C/C', 'CYP2D6*17': 'G/G', 'CYP2D6*41': 'C/C', 'DPYD*2A': 'C/C', 'DPYD*13': 'A/A', 'DPYD_HapB3': 'C/C', 'DPYD_D949V': 'T/T', 'UGT1A1*80': 'C/C'}, 'DPD947': {'CYP2D6*3': 'T/T', 'CYP2D6*4': 'C/T', 'CYP2D6*17': 'G/G', 'CYP2D6*41': 'C/C', 'DPYD*2A': 'C/C', 'DPYD*13': 'A/A', 'DPYD_HapB3': 'C/C', 'DPYD_D949V': 'T/T', 'UGT1A1*80': 'C/C'}, 'DPD948': {'CYP2D6*3': 'T/T', 'CYP2D6*4': 'C/C', 'CYP2D6*17': 'G/G', 'CYP2D6*41': 'C/C', 'DPYD*2A': 'C/C', 'DPYD*13': 'A/A', 'DPYD_HapB3': 'C/C', 'DPYD_D949V': 'T/T', 'UGT1A1*80': 'C/T'}, 'DPD949': {'CYP2D6*3': 'T/T', 'CYP2D6*4': 'C/C', 'CYP2D6*17': 'G/G', 'CYP2D6*41': 'C/C', 'DPYD*2A': 'C/C', 'DPYD*13': 'A/A', 'DPYD_HapB3': 'C/C', 'DPYD_D949V': 'T/T', 'UGT1A1*80': 'T/T'}, 'DPD950': {'CYP2D6*3': 'T/T', 'CYP2D6*4': 'C/C', 'CYP2D6*17': 'G/G', 'CYP2D6*41': 'C/C', 'DPYD*2A': 'C/C', 'DPYD*13': 'A/A', 'DPYD_HapB3': 'C/C', 'DPYD_D949V': 'T/T', 'UGT1A1*80': 'C/T'}, 'DPD951': {'CYP2D6*3': 'T/T', 'CYP2D6*4': 'C/T', 'CYP2D6*17': 'G/G', 'CYP2D6*41': 'C/C', 'DPYD*2A': 'C/C', 'DPYD*13': 'A/A', 'DPYD_HapB3': 'C/C', 'DPYD_D949V': 'T/T', 'UGT1A1*80': 'C/T'}, 'DPD952': {'CYP2D6*3': 'T/T', 'CYP2D6*4': 'C/C', 'CYP2D6*17': 'G/G', 'CYP2D6*41': 'C/C', 'DPYD*2A': 'C/C', 'DPYD*13': 'A/A', 'DPYD_HapB3': 'C/C', 'DPYD_D949V': 'T/T', 'UGT1A1*80': 'T/T'}, 'DPD953': {'CYP2D6*3': 'T/T', 'CYP2D6*4': 'C/C', 'CYP2D6*17': 'G/G', 'CYP2D6*41': 'C/T', 'DPYD*2A': 'C/C', 'DPYD*13': 'A/A', 'DPYD_HapB3': 'C/C', 'DPYD_D949V': 'T/T', 'UGT1A1*80': 'T/T'}}

In [5]:
#Obtener diccionario de números
pacientes_alelos_nums = {}

for paciente, genotipos in pacientes.items():
    pacientes_alelos_nums[paciente] = {}

    for poli, geno in genotipos.items():
        gen = gen_sin_alelo(poli)
        alelos = letras_a_nums(poli, geno)

        if gen not in pacientes_alelos_nums[paciente]:
            pacientes_alelos_nums[paciente][gen] = []
        pacientes_alelos_nums[paciente][gen].append(alelos)

In [6]:
#Data Frame para visualizarlo bien
pacientes_conv = {}
for paciente,genotipos in pacientes.items():
    alelos_paciente = {}

    for polimorfismo, genotipo in genotipos.items():
        alelos_paciente[polimorfismo] = letras_a_nums(polimorfismo, genotipo)

    pacientes_conv[paciente] = alelos_paciente

df_alelos = pd.DataFrame.from_dict(pacientes_conv, orient = "index")
display(df_alelos)

,CYP2D6*3,CYP2D6*4,CYP2D6*17,CYP2D6*41,DPYD*2A,DPYD*13,DPYD_HapB3,DPYD_D949V,UGT1A1*80
DPD932,*1/*1,*1/*1,*1/*17,*1/*1,*1/*1,*1/*1,*1/*HapB3,*1/*1,*1/*1
DPD933,*1/*1,*1/*1,*17/*17,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*80
DPD934,*1/*1,*1/*4,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1
DPD935,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*80
DPD936,*1/*1,*1/*1,*1/*1,*1/*41,*1/*1,*1/*1,*1/*1,*1/*1,*1/*80
DPD937,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1
DPD938,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1
DPD939,*1/*1,*1/*1,*1/*1,*1/*41,*1/*1,*1/*1,*1/*HapB3,*1/*1,*80/*80
DPD940,*1/*3,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*80
DPD941,*1/*1,*4/*4,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*80
DPD942,*1/*1,*1/*1,*1/*1,*1/*41,*1/*1,*1/*1,*1/*HapB3,*1/*1,*1/*80
DPD943,*1/*1,*1/*1,*1/*1,*1/*41,*1/*1,*1/*1,*1/*HapB3,*1/*1,*1/*80
DPD944,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1
DPD945,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1
DPD946,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1
DPD947,*1/*1,*1/*4,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1
DPD948,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*80
DPD949,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*80/*80
DPD950,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*80
DPD951,*1/*1,*1/*4,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*80
DPD952,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*1/*1,*80/*80
DPD953,*1/*1,*1/*1,*1/*1,*1/*41,*1/*1,*1/*1,*1/*1,*1/*1,*80/*80

In [7]:
# Primero se crerán cmo claves los pacientes y como valores un diccionario vacío
diplotiposPacientes = {}

#Ahora crearemos un bucle en el que vamos creando los diplotipos, juntando os genes como claves y el fenotipo final de ese gen como valor
for paciente, genotipo in pacientes_conv.items():
    fenotipo = {}
    for polimorfismo, alelo in genotipo.items():
        gen = gen_sin_alelo(polimorfismo)
        fenotipo.setdefault(gen, alelo)
        if fenotipo[gen] != alelo and alelo != "*1/*1": #En caso de que el alelo tambén sea *1/*1 o para evitar la redundancia de comparar en caso de que el propio alelo sea el valor con el que se creó el diccionario
            if fenotipo[gen]  == "*1/*1": #Si lo que hay en el diccinario es que no hay mutaciones aún, entonces solo sustituyo el valor por el nuevo alelo
                fenotipo[gen]  = alelo
            else: #Si ya hay una mutación para ese gen en el diccionario
                variacionAleloGen = fenotipo[gen].split("/")
                variacionAleloNuevo = alelo.split("/")
                listaVariaciones = (variacionAleloGen + variacionAleloNuevo)
                for i in range(len(listaVariaciones)):
                    if listaVariaciones[i] != "*1":
                        fenotipo[gen] += listaVariaciones[i] + "/"
                    fenotipo[gen] = fenotipo[gen][:-1] #Para quitar la última barra
    diplotiposPacientes[paciente] = fenotipo

#print(diplotiposPacientes)

dfDiplotipos = pd.DataFrame.from_dict(diplotiposPacientes, orient = "index")
display(dfDiplotipos)

         CYP2D6       DPYD   UGT1A1
DPD932   *1/*17  *1/*HapB3    *1/*1
DPD933  *17/*17      *1/*1   *1/*80
DPD934    *1/*4      *1/*1    *1/*1
DPD935    *1/*1      *1/*1   *1/*80
DPD936   *1/*41      *1/*1   *1/*80
DPD937    *1/*1      *1/*1    *1/*1
DPD938    *1/*1      *1/*1    *1/*1
DPD939   *1/*41  *1/*HapB3  *80/*80
DPD940    *1/*3      *1/*1   *1/*80
DPD941    *4/*4      *1/*1   *1/*80
DPD942   *1/*41  *1/*HapB3   *1/*80
DPD943   *1/*41  *1/*HapB3   *1/*80
DPD944    *1/*1      *1/*1    *1/*1
DPD945    *1/*1      *1/*1    *1/*1
DPD946    *1/*1      *1/*1    *1/*1
DPD947    *1/*4      *1/*1    *1/*1
DPD948    *1/*1      *1/*1   *1/*80
DPD949    *1/*1      *1/*1  *80/*80
DPD950    *1/*1      *1/*1   *1/*80
DPD951    *1/*4      *1/*1   *1/*80
DPD952    *1/*1      *1/*1  *80/*80
DPD953   *1/*41      *1/*1  *80/*80

In [15]:
import pandas as pd

CPIC = pd.read_excel("CYP2D6_Diplotype_Phenotype_Table.xlsx")

def fenotipo_asignar(diplotipo):
    
    if diplotipo in CPIC["CYP2D6 Diplotype"].values:
        fenotipo = CPIC.loc[CPIC["CYP2D6 Diplotype"] == diplotipo, "Coded Diplotype/Phenotype Summary"].values[0]
        score = CPIC.loc[CPIC["CYP2D6 Diplotype"] == diplotipo, "Activity Score"].values[0]
    else:
        fenotipo = "Unknown"
        score = "Unknown"
    return score, fenotipo

solucion = {}

for paciente, genes in diplotiposPacientes.items():
    solucion[paciente] = {}
    for gen, diplotipo in genes.items():
        if gen == "CYP2D6":
            score, fenotipo = fenotipo_asignar(diplotipo)
            solucion[paciente][gen] = {"Diplotype": diplotipo, "Activity Score": score, "Phenotype": fenotipo}
        elif gen == "DPYD":
            if diplotipo == "*1/*HapB3":
                solucion[paciente][gen] = {"Diplotype": diplotipo,"Activity Score": "N/A",  "Phenotype": "Intermediate Metabolizer"}
            else:
                solucion[paciente][gen] = {"Diplotype": diplotipo,"Activity Score": "N/A", "Phenotype": "Normal Metabolizer"}
        else:
            if diplotipo == "*1/*80":
                solucion[paciente][gen] = {"Diplotype": diplotipo,"Activity Score": "N/A", "Phenotype": "Intermediate Metabolizer"}
            elif diplotipo == "*80/*80":
                solucion[paciente][gen] = {"Diplotype": diplotipo,"Activity Score": "N/A", "Phenotype": "Poor Metabolizer"}
            else:
                solucion[paciente][gen] = {"Diplotype": diplotipo,"Activity Score": "N/A", "Phenotype": "Normal Metabolizer"}
            


filas_df = []
for paciente, info_genes in solucion.items():
    fila = {"Paciente": paciente}
    for gen, datos in info_genes.items():
        if gen == "CYP2D6":
            fila[f"{gen}_Diplotipo"] = datos["Diplotype"]
            fila[f"{gen}_Score"] = datos["Activity Score"]
            fila[f"{gen}_Fenotipo"] = datos["Phenotype"]
        else:
            fila[f"{gen}_Diplotipo"] = datos["Diplotype"]
            fila[f"{gen}_Fenotipo"] = datos["Phenotype"]
    filas_df.append(fila)

df_resultados = pd.DataFrame(filas_df)  
display(df_resultados)

,Paciente,CYP2D6_Diplotipo,CYP2D6_Score,CYP2D6_Fenotipo,DPYD_Diplotipo,DPYD_Fenotipo,UGT1A1_Diplotipo,UGT1A1_Fenotipo
0,DPD932,*1/*17,1.5,Normal Metabolizer,*1/*HapB3,Intermediate Metabolizer,*1/*1,Normal Metabolizer
1,DPD933,*17/*17,1.0,Intermediate Metabolizer,*1/*1,Normal Metabolizer,*1/*80,Intermediate Metabolizer
2,DPD934,*1/*4,1.0,Intermediate Metabolizer,*1/*1,Normal Metabolizer,*1/*1,Normal Metabolizer
3,DPD935,*1/*1,2.0,Normal Metabolizer,*1/*1,Normal Metabolizer,*1/*80,Intermediate Metabolizer
4,DPD936,*1/*41,1.25,Normal Metabolizer,*1/*1,Normal Metabolizer,*1/*80,Intermediate Metabolizer
5,DPD937,*1/*1,2.0,Normal Metabolizer,*1/*1,Normal Metabolizer,*1/*1,Normal Metabolizer
6,DPD938,*1/*1,2.0,Normal Metabolizer,*1/*1,Normal Metabolizer,*1/*1,Normal Metabolizer
7,DPD939,*1/*41,1.25,Normal Metabolizer,*1/*HapB3,Intermediate Metabolizer,*80/*80,Poor Metabolizer
8,DPD940,*1/*3,1.0,Intermediate Metabolizer,*1/*1,Normal Metabolizer,*1/*80,Intermediate Metabolizer
9,DPD941,*4/*4,0.0,Poor Metabolizer,*1/*1,Normal Metabolizer,*1/*80,Intermediate Metabolizer
10,DPD942,*1/*41,1.25,Normal Metabolizer,*1/*HapB3,Intermediate Metabolizer,*1/*80,Intermediate Metabolizer
11,DPD943,*1/*41,1.25,Normal Metabolizer,*1/*HapB3,Intermediate Metabolizer,*1/*80,Intermediate Metabolizer
12,DPD944,*1/*1,2.0,Normal Metabolizer,*1/*1,Normal Metabolizer,*1/*1,Normal Metabolizer
13,DPD945,*1/*1,2.0,Normal Metabolizer,*1/*1,Normal Metabolizer,*1/*1,Normal Metabolizer
14,DPD946,*1/*1,2.0,Normal Metabolizer,*1/*1,Normal Metabolizer,*1/*1,Normal Metabolizer
15,DPD947,*1/*4,1.0,Intermediate Metabolizer,*1/*1,Normal Metabolizer,*1/*1,Normal Metabolizer
16,DPD948,*1/*1,2.0,Normal Metabolizer,*1/*1,Normal Metabolizer,*1/*80,Intermediate Metabolizer
17,DPD949,*1/*1,2.0,Normal Metabolizer,*1/*1,Normal Metabolizer,*80/*80,Poor Metabolizer
18,DPD950,*1/*1,2.0,Normal Metabolizer,*1/*1,Normal Metabolizer,*1/*80,Intermediate Metabolizer
19,DPD951,*1/*4,1.0,Intermediate Metabolizer,*1/*1,Normal Metabolizer,*1/*80,Intermediate Metabolizer
20,DPD952,*1/*1,2.0,Normal Metabolizer,*1/*1,Normal Metabolizer,*80/*80,Poor Metabolizer
21,DPD953,*1/*41,1.25,Normal Metabolizer,*1/*1,Normal Metabolizer,*80/*80,Poor Metabolizer

In [17]:
import pandas as pd

tablita = []

for paciente, metabolizador in solucion.items():
    for gen, datos in metabolizador.items():
        fenotipo = datos.get("Phenotype", "")
    
        medicacion = ""
        recomendacion = ""

        if gen == "CYP2D6":
            medicacion = "Tamoxifeno"
            if fenotipo == "Poor Metabolizer":
                recomendacion = "Considerar cambio de tratamiento"
            elif fenotipo == "Intermediate Metabolizer":
                recomendacion = "Considerar reducción de la dosis"
            else:
                recomendacion = "Dosis estándar"
                
        elif gen == "DPYD":  
            medicacion = "Fluoropirimidinas"
            if fenotipo == "Poor Metabolizer":
                recomendacion = "Contraindicado. Iniciar con dosis muy reducidas"
            elif fenotipo == "Intermediate Metabolizer":
                recomendacion = "50% dosis estándar, aumentando\nsi es tolerado"
            else:
                recomendacion = "Dosis estándar"
                
        elif gen == "UGT1A1":
            medicacion = "Irinotecán"
            if fenotipo == "Poor Metabolizer":
                recomendacion = "Reducción de la dosis"
            elif fenotipo == "Intermediate Metabolizer":
                recomendacion = "Reducción de la dosis"
            else:
                recomendacion = "Dosis estándar"
            
        tablita.append({
            "Identificador paciente": paciente,
            "Gen": gen,
            "Nombre medicación": medicacion,
            "Recomendaciones": recomendacion
        })

df_resultados_finales = pd.DataFrame(tablita)  
display(df_resultados_finales)

,Identificador paciente,Gen,Nombre medicación,Recomendaciones
0,DPD932,CYP2D6,Tamoxifeno,Dosis estándar
1,DPD932,DPYD,Fluoropirimidinas,"50% dosis estándar, aumentando\nsi es tolerado"
2,DPD932,UGT1A1,Irinotecán,Dosis estándar
3,DPD933,CYP2D6,Tamoxifeno,Considerar reducción de la dosis
4,DPD933,DPYD,Fluoropirimidinas,Dosis estándar
...,...,...,...,...
61,DPD952,DPYD,Fluoropirimidinas,Dosis estándar
62,DPD952,UGT1A1,Irinotecán,Reducción de la dosis
63,DPD953,CYP2D6,Tamoxifeno,Dosis estándar
64,DPD953,DPYD,Fluoropirimidinas,Dosis estándar
65,DPD953,UGT1A1,Irinotecán,Reducción de la dosis

In [18]:
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, HRFlowable

import datetime as dt


archivo_pdf = "prueba.pdf"
logo = "logo_DrugApp.jpeg"

doc = SimpleDocTemplate(
    archivo_pdf,
    pagesize=A4,
    rightMargin=2*cm,
    leftMargin=2*cm,
    topMargin=1.5*cm,
    bottomMargin=2*cm,
    title="Informe Farmacogenético"
)

contenido = []

estilos = getSampleStyleSheet()

titulo_style = ParagraphStyle(
    "TituloPersonalizado",
    parent=estilos["Title"],
    fontName="Times-Bold",
    fontSize=15,
    leading=27,
    alignment=TA_CENTER,
    spaceAfter = 20
)

subtitulo_style = ParagraphStyle(
    "SubtituloPersonalizado",
    parent=estilos["Normal"],
    fontName="Times-Bold",
    fontSize=13,
    leading=15,
    alignment = TA_CENTER,
    spaceAfter=5
)

parrafo_style = ParagraphStyle(
    "ParrafoPersonalizado",
    parent=estilos["BodyText"],
    fontName="Times-Roman",
    fontSize=11,
    leading=15,
    alignment=TA_JUSTIFY,
    spaceAfter=10
)

seccion_style = ParagraphStyle(
    "SeccionPersonalizada",
    parent=estilos["Heading2"],
    fontName="Times-Bold",
    fontSize=11,
    leading=18,
    alignment = TA_LEFT,
    spaceBefore=12,
    spaceAfter=8
)

logo = Image(logo, width=2.2*cm, height=2*cm)

ID_PACIENTE = df_resultados_finales["Identificador paciente"].iloc[0]

cabecera_texto = [
    Spacer(1, 0.6*cm),
    Paragraph("INFORME FARMACOGENÉTICO - PERFIL ONCOLOGÍA", titulo_style),
    Paragraph(f"Código de Muestra {ID_PACIENTE}", subtitulo_style) # SE PUEDE PONER EL SUBTÍTULO POR SEPARADO EN VEZ DE METERLO EN LISTA
]

cabecera = Table([[logo], [cabecera_texto]])

cabecera.setStyle(TableStyle([
    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ("ALIGN", (0, 0), (0, 0), "LEFT"),
    ("ALIGN", (1, 0), (1, 0), "CENTER"),
    ("LEFTPADDING", (0, 0), (-1, -1), 0),
    ("RIGHTPADDING", (0, 0), (-1, -1), 0),
    ("TOPPADDING", (0, 0), (-1, -1), 4),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
]))


contenido.append(cabecera)

contenido.append(HRFlowable(
    width="100%",
    thickness=0.5,
    color=colors.black,
    spaceBefore=1,
    spaceAfter=0.5*cm
))


datos_tabla_pers = [
    [f"Paciente: {ID_PACIENTE}", f"Nº historia: {ID_PACIENTE}"],
    [f"Fecha solicitud: {dt.date.today()}", "Fecha: 21/10/2026"],
    ["Enfermedades: ", ""],
    ["", ""],
    ["Tratamientos actuales: ", ""]
]

tabla_datos = Table(
    datos_tabla_pers,
    colWidths=[10*cm, 6.5*cm],
    repeatRows=1,
    hAlign="LEFT"
)

tabla_datos.setStyle(TableStyle([
    ("FONTNAME", (0, 0), (-1, 0), "Times-Bold"),
    ("FONTSIZE", (0, 0), (-1, -1), 11),
    ("FONTNAME", (0, 1), (-1, -1), "Times-Bold"),
]))

contenido.append(tabla_datos)
contenido.append(Spacer(1, 0.5*cm))


contenido.append(HRFlowable(
    width="100%",
    thickness=0.5,
    color=colors.black,
    spaceBefore=2,
    spaceAfter=0.5*cm
))

contenido.append(Paragraph("Los siguientes polimorfismos se han analizado mediante PCR a tiempo real con tarjeta de genotipado customizada para el Servicio de Oncología en un equipo ViiA7, con el uso de sondas de hibridación TaqMan (Thermofisher).", 
                           parrafo_style))

contenido.append(Spacer(1, 0.2*cm))



# Tabla polimorfismos

datos_tabla1 = [
    ["Gen", f"Polimorfismos analizados\ncon relevancia funcional conocida", "Fármaco de interés"]
]

genes_tabla = df_resultados_finales["Gen"].unique()
polimorfismos = {}
medicamentos = {"DPYD": "Fluorouracilo", "CYP2D6": "Tamoxifeno", "UGT1A1": "Irinotecan"}

for i in range(len(df_resumen)):
    fila = df_resumen.iloc[i]
    if fila["Gen"] not in polimorfismos:
        if fila["Gen"] == "UGT1A10":
            fila["Gen"] = "UGT1A1"
        polimorfismos[fila["Gen"]] = []
    
    polimorfismos[fila["Gen"]].append(f"{fila["Polimorfismo"]} ({fila["Identificador RS"]})")


for gen in genes_tabla:
    polim = polimorfismos[gen]
    datos_tabla1.append([gen, "\n".join(polim), medicamentos[gen]])


tabla1 = Table(
    datos_tabla1,
    colWidths=[3*cm, 7.5*cm, 6*cm],
    repeatRows=1
)

tabla1.setStyle(TableStyle([
    ("FONTNAME", (0, 0), (-1, 0), "Times-Bold"),
    ("FONTSIZE", (0, 0), (-1, -1), 11),
    ("FONTNAME", (0, 1), (-1, -1), "Times-Roman"),
    ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ("TOPPADDING", (0, 0), (-1, -1), 4),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
]))

contenido.append(tabla1)
contenido.append(Spacer(1, 0.5*cm))

contenido.append(Paragraph("RESULTADOS:", seccion_style))


datos_tabla2 = [
    ["Gen", "Fenotipo", "Fármaco de interés", "Recomendación terapéutica"]
]

d_paciente = df_resultados_finales[df_resultados_finales["Identificador paciente"] == ID_PACIENTE]
df_resultados = df_resultados[df_resultados["Paciente"] == ID_PACIENTE]

for i in range(len(genes_tabla)):
    fila = d_paciente.iloc[i]
    gen = fila["Gen"]
    datos_tabla2.append([f"{gen}\n{df_resultados[f"{gen}_Diplotipo"].iloc[0]}", 
                         df_resultados[f"{gen}_Fenotipo"].iloc[0], 
                         fila["Nombre medicación"], 
                         fila["Recomendaciones"]])


tabla2 = Table(
    datos_tabla2,
    colWidths=[2.5*cm, 4.5*cm, 4*cm, 5.5*cm],
    repeatRows=1
)

tabla2.setStyle(TableStyle([
    ("FONTNAME", (0, 0), (-1, 0), "Times-Bold"),
    ("FONTSIZE", (0, 0), (-1, -1), 11),
    ("FONTNAME", (0, 1), (-1, -1), "Times-Roman"),
    ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ("ALIGN", (0, 1), (-1, -1), "LEFT"),
    ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ("TOPPADDING", (0, 0), (-1, -1), 4),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
]))

contenido.append(tabla2)

doc.build(contenido)